[package]
name = "mft_master"
version = "0.2.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
egui_extras = { version = "0.29", features = ["file"] }
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"